default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: iviutorre_development

test:
  <<: *default
  database: iviutorre_test

staging:
  <<: *default
  database: iviutorre_staging

production:
  <<: *default
  database: iviutorre_production
